site_name: "SIFKA Documentation"
site_description: "Documentation"
site_url: "https://rixlux.github.io/SIFKA/"

repo_name: "RixLux/SIFKA"
repo_url: "https://github.com/RixLux/SIFKA"

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - i18n:
      languages:
        - locale: id
          name: Bahasa Indonesia
          build: true
        - locale: en
          default: true
          name: English
          build: true
  - swagger-ui-tag
  # - render_swagger
  - git-revision-date-localized:
      enable_creation_date: !ENV [CI, false]
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - LAPORAN KEMAJUAN KELOMPOK1: LAPORAN_KEMAJUAN_KELOMPOK1.md
  - PRD: PRD.md
  - Custom Artisan Command Guide: custom-artisan-command-guide.md
  - ImageManagement: imageManagement.md
  - Migration Guide: migration_guide.md
  - Environment Guide: env_guide.md
